export const USER_ROLES = {
  JOB_SEEKER: "job_seeker",
  RECRUITER: "recruiter",
};

export const APPLICATION_STATUSES = {
  APPLIED: "applied",
  REVIEWED: "reviewed",
  INTERVIEWING: "interviewing",
  ACCEPTED: "accepted",
  REJECTED: "rejected",
};

export const APPLICATION_STATUS_LIST = [
  APPLICATION_STATUSES.APPLIED,
  APPLICATION_STATUSES.REVIEWED,
  APPLICATION_STATUSES.INTERVIEWING,
  APPLICATION_STATUSES.ACCEPTED,
  APPLICATION_STATUSES.REJECTED,
];
